name: Create Prod Release
on:
  workflow_dispatch:

jobs:
  merge_main_to_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Merge main to release
        run: |
          git checkout main
          git pull
          git checkout release
          git pull
          git merge main --ff-only
          git push
