name: Create Prod Release
on:
  workflow_dispatch:

jobs:
  merge_main_to_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: test secrets
        run: |
          echo ${{ secrets.TEST_SECRETS }} | wc
      - name: Merge main to release
        run: |
          git checkout release
          git merge main --ff-only
          git push
