name: Release
on:
  push:
    branches:
      - release

jobs:
  do_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: echo "hello world"
